### PR TITLE
Mapsurfer update

### PR DESCRIPTION
**Pull request by joker234**
Cleaned OpenMapSurfer entries and fixed tiles/terms_of_use.

Please don't hesitate to remove the old MapSurfer entries using the url of korona, since this server is no longer available. The last PR of @mcauer (#184) introduced a [new entry](https://qms.nextgis.com/geoservices/2570/), but the [old one](https://qms.nextgis.com/geoservices/443/) is still in the database.

Thanks a lot.

### CODE REVIEW

**Comment by simgislab** [comment]
would you mind also creating entries at qms.nextgis.com? will be happy to remove old ones after that. Thanks.

**Comment by joker234** [comment]
Done. The only thing left would be a change of the terms-of-use in [the newly created entry](https://qms.nextgis.com/geoservices/2570/) and the deletion of all old mapsurfer layers. I could change the terms-of-use in 2570, by myself, if I (nextgis username Joker234) get the permissions to change them in this entry.

I just saw, that the old entries are also in the MapSurfer.NET group. Is it possible to change them in there, too? Presumably with the next plugin update of qms.

**Comment by simgislab** [comment]
thank you! can you please recreate the new one? I'll remove 2570

It's much better if maintainer would be someone who is not me :)

**Comment by joker234** [comment]
@simgislab thx for releasing the plugin in July, but it seems that it wasn't published in the QGIS Plugin Database https://planet.qgis.org/plugins/quick_map_services

**Comment by simgislab** [comment]
now published

**Pull request merged**
